// <auto-generated />
using System;
using Ivao.It.DiscordBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ivao.It.DiscordBot.Data.Migrations
{
    [DbContext(typeof(DiscordDbContext))]
    [Migration("20211214093017_GdprDateTime")]
    partial class GdprDateTime
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ivao.It.DiscordBot.Data.User", b =>
                {
                    b.Property<string>("IvaoVid")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<DateTime?>("GdprAcceptDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("varchar(70)");

                    b.Property<string>("Otp")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.HasKey("IvaoVid");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
